### ISSUE TITLE
helpers.php

### ISSUE THREAD

**Issue by josteph** [Internetcodehq/laravel-user-settings#4]
Remove `helpers.php` or add new line in `helpers.php` below `<?php`

**Comment by Taronyuu** [comment]
I'm sure you have a valid reason for this... But why? 🤔

**Comment by josteph** [comment]
Hello, sorry for the lack of explanation.

The other day, after a fresh installation of this package and Laravel 5.6, I encountered:
`Unexpected end of file <?php at helpers.php line 1`
when doing `composer dumpautoload`.

After adding new line after `<?php`, it didn't give any error anymore.

**Comment by Taronyuu** [comment]
Seems fair, removed the helpers file!

Thanks for notifying me. 😄
